version: '3.8'
services:
  web:
    image: docker.io/library/nginx:stable-alpine3.21-perl
    expose:
      - 80
    # volumes:
    #   - ./html5up-stellar/:/usr/share/nginx/html
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-app.rule=Host('web-dev.xyretail.site')
      - traefik.http.routers.web-app.entrypoints=web
      - traefik.http.services.web-app.loadbalancer.server.port=80
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.env==dev

networks:
  dokploy-network:
    external: true
